pipeline {
    agent any

    stages {

        stage('checkout') {
            steps {
                deleteDir()
                checkout scm
            }
        }
        
        stage('run shell') {
            steps {
                dir("pipeline") {
                    sh "./shell.sh" 
                }
            }   
        }
    }

    post {
        failure {
            cat env.txt
        }
    }
}
